name: graph-exp-core
channels:
  - pytorch
  - pyg
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - numpy
  - scipy
  - scikit-learn
  - networkx
  - pip
  - pip:
      - torch-geometric
